[package]
name = "mango_engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "mango_engine"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }
walkdir = "2.4.0"
rayon = "1.8.1"
md5 = "0.7.0"
crc32fast = "1.3.2"
reqwest = { version = "0.12", features = ["json", "stream", "rustls-tls-native-roots", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.40", features = ["full", "rt-multi-thread"] }
zip = "0.6.3"
rusqlite = { version = "0.32", features = ["bundled"] }
futures = "0.3"
anyhow = "1.0"
futures-util = "0.3.31"
tokio-util = { version = "0.7.12", features = ["compat"] }
fuzzy-matcher = "0.3.7"
strsim = "0.11"
urlencoding = "2.1"
