"""
constants.py — Diccionarios y configuraciones fijas del sistema
Aquí se definen los emuladores soportados y sus metadatos de Libretro.
"""

AVAILABLE_EMULATORS = [
    {
        "id": "retroarch",
        "name": "RetroArch",
        "console": "Multi-system",
        "console_id": "multi",
        "description": "El frontend más potente para emulación. Permite ejecutar múltiples núcleos (consolas) desde una sola interfaz.",
        "folder": "Multi",
        "github": "libretro/RetroArch",
        "manual_url": "https://www.retroarch.com/index.php?page=platforms",
        "fallback_win": "https://buildbot.libretro.com/stable/1.17.0/windows/x86_64/RetroArch.7z",
        "fallback_linux": "https://buildbot.libretro.com/stable/1.17.0/linux/x86_64/RetroArch.7z",
        "extensions": [".bin", ".cue", ".rom", ".zip"],
        "libretro_platform": None,
        "color": "#9b9b9b" # Gray
    },
    {
        "id": "dolphin",
        "name": "Dolphin Emulator",
        "console": "GameCube / Wii",
        "console_id": "gc-wii",
        "description": "Emulador de GameCube y Wii de alto rendimiento. Soporta gráficos en HD y juego en red.",
        "folder": "GameCube-Wii",
        "github": "dolphin-emu/dolphin",
        "manual_url": "https://dolphin-emu.org/download/",
        "fallback_win": "https://dl.dolphin-emu.org/builds/80/86/dolphin-master-2603-14-x64.7z",
        "extensions": [".iso", ".wbfs", ".gcm", ".rvz"],
        "libretro_platform": "Nintendo - GameCube",
        "color": "#6350E1" # Purple
    },
    {
        "id": "pcsx2",
        "name": "PCSX2",
        "console": "PlayStation 2",
        "console_id": "ps2",
        "description": "El emulador estándar de PlayStation 2. Compatible con la inmensa mayoría del catálogo de PS2.",
        "folder": "PS2",
        "github": "PCSX2/pcsx2",
        "manual_url": "https://pcsx2.net/downloads/",
        "fallback_url": None,
        "extensions": [".iso", ".bin", ".chd", ".gz"],
        "libretro_platform": "Sony - PlayStation 2",
        "color": "#003087" # Sony Blue
    },
    {
        "id": "rpcs3",
        "name": "RPCS3",
        "console": "PlayStation 3",
        "console_id": "ps3",
        "description": "Emulador y debugger experimental de PlayStation 3 en lenguaje C++ para Windows, Linux y BSD.",
        "folder": "PS3",
        "github": "RPCS3/rpcs3",
        "github_win": "RPCS3/rpcs3-binaries-win",
        "github_linux": "RPCS3/rpcs3-binaries-linux",
        "manual_url": "https://rpcs3.net/download",
        "fallback_linux": "https://github.com/RPCS3/rpcs3-binaries-linux/releases/download/continuous/rpcs3-v0.0.30-15900-linux-x86_64.AppImage",
        "extensions": [".ps3", ".pkg", ".iso"],
        "libretro_platform": "Sony - PlayStation 3",
        "color": "#1a1a1a" # Black
    },
    {
        "id": "ppsspp",
        "name": "PPSSPP",
        "console": "PlayStation Portable",
        "console_id": "psp",
        "description": "Emulador de PSP rápido y portátil. Permite jugar en HD y soporta texturas personalizadas.",
        "folder": "PSP",
        "github": "hrydgard/ppsspp",
        "manual_url": "https://www.ppsspp.org/downloads/",
        "fallback_url": None,
        "extensions": [".iso", ".cso", ".pbp"],
        "libretro_platform": "Sony - PlayStation Portable",
        "color": "#21409A" # PSP Blue
    },
    {
        "id": "duckstation",
        "name": "DuckStation",
        "console": "PlayStation 1",
        "console_id": "ps1",
        "description": "Enfocado en la jugabilidad, velocidad y mantenibilidad a largo plazo de la primera PlayStation.",
        "folder": "PS1",
        "github": "stenzek/duckstation",
        "manual_url": "https://www.duckstation.org/",
        "fallback_win": "https://github.com/stenzek/duckstation/releases/latest/download/duckstation-windows-x64-release.zip",
        "extensions": [".bin", ".cue", ".chd", ".pbp", ".m3u"],
        "libretro_platform": "Sony - PlayStation",
        "color": "#E60012" # PS1 Acccent (Reddish or Light Gray) - Let's use Nintendo Red for Nintendo later
    },
    {
        "id": "xemu",
        "name": "xemu",
        "console": "Original Xbox",
        "console_id": "xbox",
        "description": "Emulador de baja latencia y alta precisión de la Xbox original.",
        "folder": "Xbox",
        "github": "xemu-project/xemu",
        "manual_url": "https://xemu.app/docs/download/",
        "fallback_url": None,
        "extensions": [".iso", ".xbe"],
        "libretro_platform": "Microsoft - Xbox",
        "color": "#107C10" # Xbox Green
    },
    {
        "id": "mgba",
        "name": "mGBA",
        "console": "Game Boy Advance",
        "console_id": "gba",
        "description": "Emulador de GBA rápido y preciso. También soporta Game Boy y Game Boy Color.",
        "folder": "GBA",
        "github": "mgba-emu/mgba",
        "manual_url": "https://mgba.io/downloads/",
        "fallback_url": None,
        "extensions": [".gba", ".gbp", ".zip"],
        "libretro_platform": "Nintendo - Game Boy Advance",
        "color": "#8b1d90" # Purple GBA
    },
    {
        "id": "rmg",
        "name": "RMG (Rosalie's Mupen GUI)",
        "console": "Nintendo 64",
        "console_id": "n64",
        "description": "Interfaz moderna para Mupen64Plus centrada en la facilidad de uso y alta compatibilidad.",
        "folder": "N64",
        "github": "Rosalie241/RMG",
        "manual_url": "https://github.com/Rosalie241/RMG/releases",
        "fallback_url": None,
        "extensions": [".z64", ".n64", ".v64"],
        "libretro_platform": "Nintendo - Nintendo 64",
        "color": "#e60012" # N64 Red
    },
    {
        "id": "mesen",
        "name": "Mesen",
        "console": "NES / SNES",
        "console_id": "snes",
        "description": "Multi-emulador altamente preciso para NES, Game Boy, SNES, Master System y más.",
        "folder": "NES-SNES",
        "github": "SourMesen/Mesen2",
        "manual_url": "https://www.mesen.ca/",
        "fallback_url": None,
        "extensions": [".nes", ".sfc", ".smc", ".zip"],
        "libretro_platform": "Nintendo - Nintendo Entertainment System",
        "color": "#e22216" # NES Red
    },
    {
        "id": "snes9x",
        "name": "Snes9x",
        "console": "SNES",
        "console_id": "snes",
        "description": "Emulador de Super Nintendo clásico, ligero y altamente compatible.",
        "folder": "SNES",
        "github": "snes9xgit/snes9x",
        "manual_url": "https://www.snes9x.com/",
        "fallback_url": None,
        "extensions": [".sfc", ".smc", ".zip"],
        "libretro_platform": "Nintendo - Super Nintendo Entertainment System",
        "color": "#4b0082" # SNES Purple
    },
    {
        "id": "lime3ds",
        "name": "Lime3DS",
        "console": "Nintendo 3DS",
        "console_id": "3ds",
        "description": "Sucesor espiritual de Citra, optimizado para emular la Nintendo 3DS en hardware moderno.",
        "folder": "3DS",
        "github": "Lime3DS/Lime3DS",
        "manual_url": "https://lime3ds.github.io/",
        "fallback_url": None,
        "extensions": [".3ds", ".cia", ".app"],
        "libretro_platform": "Nintendo - Nintendo 3DS",
        "color": "#00AEEF" # Blue 3DS
    },
    {
        "id": "eden",
        "name": "Eden Emulator",
        "console": "Nintendo Switch",
        "console_id": "switch",
        "description": "Sucesor potente basado en Yuzu. Eden es actualmente uno de los emuladores de Switch más activos y con mejor rendimiento.",
        "folder": "Switch-Eden",
        "github": "eden-emulator/eden",
        "manual_url": "https://git.eden-emu.dev/eden-emu/eden/releases",
        "fallback_win": "https://git.eden-emu.dev/eden-emu/eden/releases",
        "extensions": [".nsp", ".xci"],
        "libretro_platform": "Nintendo - Switch",
        "color": "#00d2ff" 
    },
    {
        "id": "ryubing",
        "name": "Ryubing (Ryujinx Fork)",
        "console": "Nintendo Switch",
        "console_id": "switch",
        "description": "Fork moderno de Ryujinx enfocado en mejoras de calidad de vida y compatibilidad para la emulación de Switch.",
        "folder": "Switch-Ryubing",
        "github": "Ryubing/Ryujinx",
        "manual_url": "https://ryujinx.app/download",
        "fallback_win": "https://ryujinx.app/download",
        "extensions": [".nsp", ".xci"],
        "libretro_platform": "Nintendo - Switch",
        "color": "#e60012" # Switch Red
    },
    {
        "id": "cemu",
        "name": "Cemu",
        "console": "Wii U",
        "console_id": "wiiu",
        "description": "El emulador definitivo de Wii U. Permite jugar a Breath of the Wild y otros títulos a 4K y 60fps.",
        "folder": "WiiU",
        "github": "cemu-project/Cemu",
        "manual_url": "https://cemu.info/",
        "extensions": [".wud", ".wux", ".rpx"],
        "libretro_platform": "Nintendo - Wii U",
        "color": "#0096d2"
    },
    {
        "id": "vita3k",
        "name": "Vita3K",
        "console": "PS Vita",
        "console_id": "psvita",
        "description": "El primer emulador funcional de PlayStation Vita en el mundo.",
        "folder": "PSVita",
        "github": "Vita3K/Vita3K",
        "manual_url": "https://vita3k.org/",
        "extensions": [".vpk", ".zip", ".pkg"],
        "libretro_platform": "Sony - PlayStation Vita",
        "color": "#1f1f1f"
    }
]
